# ğŸ¨ Theme
[general]
import = ["~/.config/alacritty/themes/dracula-pro.toml"]
live_config_reload = true

# ğŸ”¤ Font settings
[font]
builtin_box_drawing = true
size = 12.0  

[font.normal]
family = "Source Code Pro" 
style = "Regular"

[font.bold]
family = "Source Code Pro"  # ç²—ä½“ä¹Ÿä½¿ç”¨ Source Code Pro
style = "Bold"

[font.bold_italic]
family = "Source Code Pro"  # ç²—æ–œä½“
style = "Bold Italic"

[font.italic]
family = "Source Code Pro"  # æ–œä½“
style = "Italic"

# â• Terminal environment
[env]
TERM = "alacritty"

# ğŸ–± Mouse behavior
[mouse]
hide_when_typing = true

# ğŸ–‹ Cursor style
[cursor]
unfocused_hollow = false

[cursor.style]
blinking = "Always"
shape = "Beam"

# ğŸ“œ Scrolling
[scrolling]
history = 100000
multiplier = 6

# ğŸ” Text selection
[selection]
save_to_clipboard = true
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

# ğŸ–¥ï¸ Window behavior
[window]
decorations = "None"  # ç¦ç”¨æ ‡é¢˜æ å’Œè¾¹æ¡†
dynamic_title = true
opacity = 0.75
title = "Alacritty"
padding = { x = 10, y = 10 }  # x: æ°´å¹³è¾¹è·ï¼Œy: å‚ç›´è¾¹è·ï¼ˆå•ä½ï¼šåƒç´ ï¼‰
dynamic_padding = true        # è‡ªé€‚åº”å†…è¾¹è·ï¼Œéšçª—å£å¤§å°è°ƒæ•´

[window.class]
general = "Alacritty"
instance = "Alacritty"

# ğŸŒˆ Color options
[colors]
draw_bold_text_with_bright_colors = true

# ğŸ”— URL hints
[[hints.enabled]]
command = "firefox"
hyperlinks = true
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
post_processing = true
persist = false
regex = "(https?://[^\"]+)"

# âŒ¨ï¸ Keybindings
[[keyboard.bindings]]
ACTION = "PASTE"
KEY = "v"
MODS = "CONTROL"

[[keyboard.bindings]]
action = "Copy"
key = "c"
mods = "CONTROL"

# ğŸš Default shell
[terminal.shell]
program = "/usr/bin/fish"

